version: "3"
services :
  user_service:
    container_name: users 
    restart: always
    build: .
    image: users:latest
    ports:
      - "80:8000"
    links:
      - user_mongodb
  user_mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
